[package]
name = "gotham-client"
version = "0.1.0"
authors = ["gbenattar <g.benattar@gmail.com>"]
edition = "2018"

[lib]
name = "client_lib"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
time = "*"
clap = { version = "2.32", features = ["yaml"] }