[package]
name = "gotham-server"
version = "0.1.0"
authors = ["gbenattar <g.benattar@gmail.com>"]
edition = "2018"

[lib]
name = "server_lib"
path = "src/lib.rs"

[[bin]]
name = "server_exec"
path = "src/main.rs"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
rocksdb = "0.10.1"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
uuid = { version = "0.7", features = ["v4"] }

[dependencies.zk-paillier]
git = "https://github.com/KZen-networks/zk-paillier"

[dependencies.kms]
git = "https://github.com/KZen-networks/kms"
branch = "schnorr_support"

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"
branch = "pdl-sub-protocol"

[dependencies.curv]
git = "https://github.com/KZen-networks/curv"
features =  ["curvesecp256k1"]

[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }