[package]
name = "gotham-server"
version = "0.1.0"
authors = ["gbenattar <g.benattar@gmail.com>"]
edition = "2018"

[lib]
name = "server_lib"
path = "src/lib.rs"

[[bin]]
name = "server_exec"
path = "src/main.rs"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"

[dependencies.kms]
git = "https://github.com/KZen-networks/kms"
branch = "schnorr_support"

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"
branch = "pdl-sub-protocol"

[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }